import Head from 'next/head'
import RecentOrders from '@/components/RecentOrders'
import { FaGithub, FaSearch, FaYoutube, FaRobot, FaClipboardList, FaFilter, FaCheckSquare, FaEye, FaChartPie, FaExchangeAlt } from 'react-icons/fa';


export default function Home() {
  return (
    <>
      <Head>
        <title>InfoJobs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100 min-h-screen">

        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <div className='w-full md:col-span-2 '>

            <div className='lg:col-span-3 col-span-2 bg-white flex flex-col justify-between w-full border rounded-lg'>
              <div className='flex items-center m-2'>
                <FaYoutube className='text-red-600 mr-2 w-24 h-24' />
                <p className='text-xs text-center'>
                  ¡Te invitamos a disfrutar de nuestro increíble video explicativo de 2 puntos de este desarrollo! Además, no te pierdas la oportunidad de explorar la vista de consumo de la API con filtros personalizados y muchas más opciones disponibles. Asegúrate de desplazarte hacia abajo para obtener más información sobre las demás características. ¡Esperamos que lo disfrutes!
                </p>
              </div>
              <a href="https://youtu.be/Va7s3XM_gJI" target="_blank" rel="noreferrer" className='text-center hover:font-bold'>LINK DEL VIDEO</a>
            </div>

            <div className='lg:col-span-3 mt-3 col-span-2 bg-white flex flex-col justify-between w-full border p-4 rounded-lg'>
              <div className='flex items-center'>
                <FaRobot className=' ml-5  w-14 h-14' />
                <p className='text-2xl font-bold text-center'>
                  Potencia tu Búsqueda Laboral y Analiza el Mercado de Forma Precisa, sin inteligencia artificial
                </p>
              </div>

              <div className='text-sm mt-1'>
                <p className='text-gray-500 text-center'>Descubre este proyecto en dos partes:</p>
                <div className='grid grid-cols-1 md:grid-cols-2 gap-4 mt-5 m-5'>

                  {/* Informacion Frond */}
                  <div className='text-left'>
                    <p className='font-bold text-center'>FRONTEND</p>
                    <div className='flex items-center mt-2 hover:bg-gray-50 rounded-lg'>
                      <FaSearch className='mr-2 w-6 h-6' />
                      <p className='text-gray-600'>Optimizando la búsqueda de empleo: Un enfoque innovador basado en habilidades y feedback personalizado</p>
                    </div>
                    <div className='flex items-center mt-2 hover:bg-gray-50 rounded-lg'>
                      <FaCheckSquare className='mr-2' />
                      <p className='text-gray-600'>Potencia tu búsqueda laboral: revisa, evalúa y avanza en el proceso de selección</p>
                    </div>
                    <div className='flex items-center mt-2 hover:bg-gray-50 rounded-lg'>
                      <FaEye className='mr-2' />
                      <p className='text-gray-600'>Descubre las empresas que han revisado tu perfil, ofertas y calificaciones</p>
                    </div>
                    <div className='flex items-center mt-2 hover:bg-gray-50 rounded-lg'>
                      <FaExchangeAlt className='mr-2' />
                      <p className='text-gray-600'>Explora infinitas oportunidades laborales: accede a una API sin restricciones en Infojobs</p>
                    </div>
                    <div className='flex items-center mt-2 hover:bg-gray-50 rounded-lg'>
                      <FaChartPie className='mr-2' />
                      <p className='text-gray-600'>Explora el mercado laboral: análisis, gráficos y gestión personalizada de tu perfil</p>
                    </div>
                    <div className='flex items-center mt-2 hover:bg-gray-50 rounded-lg'>
                      <FaGithub className='mr-2' />
                      <p className='text-gray-600'>Repositorio: <a className='hover:font-bold' href="https://github.com/Jucamhc/frond-infojobs.git" target="_blank" rel="noreferrer"> https://github.com/Jucamhc/frond-infojobs.git </a> </p>
                    </div>
                  </div>
                  {/* Informacion Back */}
                  <div className='text-left'>
                    <p className='font-bold text-center'>BACKEND</p>
                    <div className='flex items-center mt-2 hover:bg-gray-50 rounded-lg'>
                      <FaClipboardList className='mr-2 w-5 h-5' />
                      <p className='text-gray-600'>Utiliza mi hoja de vida en formato de array según los estándares de Infojobs</p>
                    </div>
                    <div className='flex items-center mt-2 hover:bg-gray-50 rounded-lg'>
                      <FaFilter className='mr-2' />
                      <p className='text-gray-600'>Consume y realiza filtros de todas las ofertas públicas de Infojobs</p>
                    </div>
                    <div className='flex items-center mt-2 hover:bg-gray-50 rounded-lg'>
                      <FaGithub className='mr-2' />
                      <p className='text-gray-600'>Repositorio: <a className='hover:font-bold' href="https://github.com/Jucamhc/api-infojobs-hackathon" target="_blank" rel="noreferrer"> https://github.com/Jucamhc/api-infojobs-hackathon </a> </p>
                    </div>
                  </div>

                </div>
              </div>
            </div>


            <div className='mt-2 lg:col-span-3 col-span-2 bg-white flex justify-between w-full border p-4 rounded-lg'>
              <div className='flex flex-col w-full pb-4'>
                <p className='text-1xl font-bold'>INFORMACION</p>
                <div className=' items-center mt-2 mr-5'>
                  <p className='text-sm'>La plataforma ha sido diseñada considerando el inicio de sesión del perfil de Juan Camilo. Al buscar empleo, recibirás un feedback personalizado sobre las ofertas en el campo de Informática-Telecomunicaciones, con especial enfoque en el desarrollo de software. En el backend, se compara la hoja de vida, almacenada en un array simulando la consulta al usuario que inicio session, con cada una de las ofertas disponibles. Además, en la vista del perfil, se lleva a cabo la gestión del análisis del mercado laboral por la categoria preferido por el usuario utilizando todas las ofertas publicadas relacionadas en InfoJobs, garantizando que la información en esta plataforma demo esté siempre actualizada y completa.</p>
                </div>
              </div>
            </div>



            <div className='mt-2 lg:col-span-3 col-span-2 bg-white flex justify-between w-full border p-4 rounded-lg'>
              <div className='flex flex-col w-full pb-4'>
                <p className='text-2xl font-bold'>Presentacion de la Web</p>
                <div className=' items-center mt-2 mr-5'>

                  <p className='text-1xl font-bold'>FRONTEND</p>
                  <p className='mt-5'>Motor de busqueda con Feedback personalizado</p>
                  <ul className='flex'>
                    <li className='flex'>
                      <FaSearch className='mr-4  w-28 h-28' />
                      <div className='text-gray-600 text-sm mt-4'>
                        <p>En búsqueda de una solución aplicable al core del negocio de facilitar la búsqueda de empleo basada en las habilidades individuales, me percaté de que resultaba demasiado costoso comparar cada oferta laboral con mi currículum con IA para brindar un feedback personalizado. Fue entonces cuando encontré una manera de ayudar a los candidatos a encontrar ofertas que se alinearan con sus habilidades.</p>
                        <br />
                        <p>Al examinar las hojas de vida en la plataforma de Infojobs, descubrí que el frond recibe la información de la hoja de vida en forma de array. Esta observación me inspiró a generar una idea innovadora. Aprovechando el array, desarrollé una consulta que extrae las habilidades de mis empleos anteriores y mis habilidades que e puesto en general. Luego, eliminé las duplicidades y obtuve un array limpio que contenía todas las habilidades relevantes. Esta lista de habilidades fue integrada en mi CV, junto con los datos de las hojas de vida y cree la misma CV con diferencia a un objeto dentro, accesibles a través de https://api-jucamhc.hop.sh/filtradoSkill.</p>
                        <br />
                        <p> Con el array de mi currículum también pude encontrar la forma en la que se genera la consulta de las ofertas laborales, comencé a iterar cada una de ellas y en el campo de descripción, busqué las habilidades que coincidieran con las mencionadas en la oferta. Cada vez que encontraba una coincidencia, otorgo un punto y creo un nuevo array que contenía las ofertas, enriquecidas con una puntuación personalizada según el perfil del candidato, este proceso se repetía para cada perfil, generando un feedback inmediato y preciso para cada empleo.</p>
                        <br />
                        <p>Calculé el análisis de cada oferta laboral con respecto a mis habilidades mediante el query realizado, lo que implicó un tiempo aproximado de 600 ms por cada 20 empleos, incluyendo la llamada al endpoint, ya que no cuento con dinero para adquirir la API de OpenAi, llevé a cabo este proceso manualmente utilizando ChatGPT 3.5, lo cual tomaba aproximadamente 260 ms por cada empleo dando un total por 20 empleos de 5.200ms. En total, se logró reducir el tiempo en un 86% en comparación con la respuesta del usuario, proporcionando así un feedback valioso para encontrar las mejores ofertas que se ajustaran a las habilidades proporcionadas por cada individuo.</p>
                        <br />
                        <p>De esta forma la búsqueda de empleo es más precisa y personalizada. Al aprovechar las habilidades y las descripciones de las ofertas laborales, se optimiza el proceso de emparejamiento entre candidatos y empleadores, brindando resultados satisfactorios para ambas partes.</p>
                      </div>
                    </li>
                  </ul>

                  <p className='mt-5'>Potencia tu búsqueda laboral: Revisa, Evalúa y Avanza en el proceso de selección</p>
                  <ul>
                    <li className='flex'>
                      <FaCheckSquare className='mr-4  w-20 h-20' />
                      <div className='text-gray-600 text-sm mt-4'>
                        <p>La plataforma va más allá de la búsqueda y postulación a ofertas laborales, te proporcionamos una herramienta innovadora para revisar y evaluar tus aplicaciones, brindándote información relevante sobre las ofertas a las que te has postulado y evaluando tu adaptabilidad en el mercado laboral.</p>
                        <br />
                        <p>Imagina tener una vista mejorada donde visualices todas tus aplicaciones laborales, hemos desarrollado dos campos clave en nuestra tabla: adaptabilidad y proceso, en adaptabilidad verás el porcentaje de compatibilidad de tu perfil con cada oferta, mostrándote cuánto encajas con las necesidades que requieren las empresas. En proceso, podrás seguir el avance de tus postulaciones en cada etapa de selección, con cinco etapas claras (aplicada, CV vista, en proceso, finalista, contratado o proceso finalizado). Esta información te permitirá evaluar tu progreso y saber en qué etapa te encuentras en cada postulación.</p>
                        <br />
                        <p>Pero eso no es todo. También podrás ver datos adicionales como la cantidad de aplicantes, país y nombre de la empresa. Queremos brindarte un entorno profesional y completo para tomar decisiones informadas en tu búsqueda laboral.</p>
                        <br />
                        <p>Además, hemos incluido dos ofertas patrocinadas para una experiencia publicitaria y generar ingresos para mejorar nuestros servicios.</p>
                        <br />
                        <p>Nuestra plataforma te ofrece herramientas poderosas para revisar aplicaciones, evaluar adaptabilidad y seguir el proceso de selección de manera eficiente. Prepárate para potenciar tu búsqueda de empleo y tener una visión clara del mercado laboral.</p>
                      </div>
                    </li>
                  </ul>

                  <p className='mt-5'>Descubre las Empresas que han Revisado tu Perfil, Ofertas y Calificaciones</p>
                  <ul>
                    <li className='flex'>
                      <FaEye className='mr-4  w-28 h-28' />
                      <div className='text-gray-600 text-sm mt-4'>
                        <p>Obtén una visión completa de tu perfil laboral: Explorando las empresas que han revisado tu perfil y evaluando sus ofertas y calificaciones. Encontrarás una sección dedicada a proporcionarte información valiosa sobre la interacción de las empresas con tu perfil, permitiéndote tomar decisiones informadas en tu búsqueda de empleo</p>
                        <br />
                        <p>En esta sección, encontrarás una tabla organizada en cinco columnas que incluyen:</p>
                        <br />
                        <p className='ml-5'>1. Nombre de la empresa: Descubre qué empresas han mostrado interés en tu perfil laboral y han revisado tu información. Esto te brinda una perspectiva de las organizaciones que podrían estar interesadas en contratarte.</p>
                        <br />
                        <p className='ml-5'>2. País: Obtén información sobre la ubicación geográfica de las empresas que han revisado tu perfil. Esto puede ser útil si tienes preferencias de ubicación o si estás interesado en explorar oportunidades en diferentes países.</p>
                        <br />
                        <p className='ml-5'>3. Cantidad de empleados: Conoce el tamaño de cada empresa que ha evaluado tu perfil. Esto puede darte una idea de la estructura y el alcance de las organizaciones que podrían estar interesadas en tu perfil laboral.</p>
                        <br />
                        <p className='ml-5'>4. Ofertas a las que se puede aplicar: Descubre las oportunidades laborales que estas empresas tienen disponibles y a las que puedes postularte. Esto te permite explorar las posibles opciones de empleo que se alinean con tus intereses y habilidades.</p>
                        <br />
                        <p className='ml-5'>5. Calificación y comentarios: Obtén una perspectiva adicional sobre las empresas y sus ofertas a través de las calificaciones y comentarios proporcionados. Estos datos te permiten evaluar la reputación y el feedback de otros candidatos, lo cual es valioso para tomar decisiones informadas en tu búsqueda laboral.</p>
                        <br />
                        <p >Esta sección te brinda información detallada sobre las interacciones de las empresas con tu perfil laboral, desde las que han revisado tu información hasta las ofertas disponibles y las opiniones de otros candidatos. Aprovecha esta funcionalidad para potenciar tu búsqueda de empleo y obtener una visión más completa de las oportunidades laborales que se adaptan a tus necesidades y aspiraciones profesionales.</p>
                      </div>
                    </li>
                  </ul>

                  <p className='mt-5'>Explora Infinitas Oportunidades Laborales: Accede a una API sin Restricciones en Infojobs</p>
                  <ul>
                    <li className='flex'>
                      <FaExchangeAlt className='mr-4  w-24 h-24' />
                      <div className='text-gray-600 text-sm mt-4'>
                        <p>Hemos desarrollado un modulo que te permitira  acceder a información laboral detallada y personalizada. Con esta API, puedes filtrar las ofertas laborales por provincia, ciudad, teletrabajo, categoría de trabajo, educación requerida, jornada laboral, tipo de contrato y país. ¡La flexibilidad de los filtros te muestra exactamente lo que estás buscando!</p>
                        <br />
                        <p>Con tan solo unos simples parámetros de búsqueda, la API te permite visualizar hasta 20 ofertas por consulta que se ajustan a tus criterios. Además, puedes iterar por medio de páginas para explorar una amplia variedad de oportunidades laborales. ¡Con estos parametros no tendras límites para tu búsqueda!</p>
                        <br />
                        <p>Acceder a todas las ofertas laborales actuales publicadas en Infojobs nunca ha sido tan fácil. Nuestra API te brinda la libertad de explorar y aprovechar al máximo todas las oportunidades disponibles. Sin restricciones y sin barreras, podrás encontrar tu próximo desafío profesional.</p>
                        <br />
                      </div>
                    </li>
                  </ul>

                  <p className='mt-5'>Explora el Mercado Laboral: Análisis, Gráficos y Gestión Personalizada de tu Perfil</p>
                  <ul>
                    <li className='flex'>
                      <FaChartPie className='mr-4  w-24 h-24' />
                      <div className='text-gray-600 text-sm mt-4'>
                        <p>En nuestra plataforma, te ofrecemos una herramienta poderosa que te brinda un análisis profundo del mercado laboral en la categoría de tu elección. Con esta función, podrás obtener información clave sobre las opciones de trabajo presenciales y teletrabajo disponibles en tu campo.</p>
                        <br />
                        <p>Además, hemos desarrollado un gráfico informativo que muestra el porcentaje de empleos presenciales y de teletrabajo en la categoría que seleccionaste. Esto te ayudará a entender las tendencias actuales del mercado y te permitirá tomar decisiones informadas sobre tu búsqueda laboral.</p>
                        <br />
                        <p>También hemos creado un fascinante gráfico de empleos por país. Este gráfico te mostrará el porcentaje de empleos disponibles en cada país, brindándote una visión clara de las oportunidades laborales en diferentes partes del mundo.</p>
                        <br />
                        <p>Pero eso no es todo lo que nuestra plataforma tiene para ofrecerte. También podrás acceder y visualizar toda tu información personal, educativa, experiencia laboral, idiomas y habilidades. Esta función te permitirá tener un perfil completo y detallado, lo cual es fundamental para destacarte en el mercado laboral y captar la atención de los empleadores.</p>
                        <br />
                        <p> plataforma te brinda una herramienta de análisis del mercado laboral que te proporciona información precisa y detallada sobre la categoría de tu elección. Además, podrás explorar gráficos interactivos sobre empleos presenciales y de teletrabajo, así como una visión global de los empleos por país. Aprovecha también la posibilidad de visualizar y gestionar toda tu información personal y profesional en un solo lugar. ¡Prepárate para descubrir los secretos del mercado laboral y potenciar tu búsqueda de empleo como nunca antes!</p>
                        <br />
                      </div>
                    </li>
                  </ul>

                  <p className='text-1xl font-bold '>BACKEND</p>

                  <p className='mt-5'>Utiliza mi hoja de vida en formato de array según los estándares de Infojobs </p>
                  <ul>
                    <li className='flex'>
                      <FaClipboardList className='mr-4  w-24 h-24' />
                      <div className='text-gray-600 text-sm mt-4'>
                        <p>En este endpoint URL: <a className='hover:font-bold' href="https://github.com/Jucamhc/api-infojobs-hackathon" target="_blank" rel="noreferrer"> https://github.com/Jucamhc/api-infojobs-hackathon </a>, tendrás acceso a un array que contiene toda mi información personal, laboral, educativa, habilidades y mucho más. Este ejemplo representa la comunicación entre el backend y el frontend de Infojobs , donde adquiero la estructura oficial de los CV que se enuentren registrados en la plataforma. </p>
                        <br />
                        <p>De acuerdo a la estrutura adquirida del objeto CV se crea un query desde donde tomo las habilidades de mis empleos anteriores y las habilidades en general que he proporcionado a la plataforma, Al final del array CV creo un ampo donde se recopilan todas las hablidades, esta integración proporciona una visión completa y organizada de mis capacidades y experiencia en un solo lugar.</p>
                      </div>
                    </li>
                  </ul>

                  <p className='mt-5'>Potencia tu búsqueda laboral con nuestra API REST: Explora ofertas personalizadas y detalladas </p>
                  <ul>
                    <li className='flex'>
                      <FaFilter className='mr-4  w-24 h-24' />
                      <div className='text-gray-600 text-sm mt-4'>
                        <p>Hemos creado una API REST endpoint URL: <a className='hover:font-bold' href="https://www.infojobs.net/webapp/offers/search?keyword=&normalizedJobTitleIds=&provinceIds=&cityIds=&teleworkingIds=&categoryIds=&workdayIds=&educationIds=&segmentId=&contractTypeIds=&page=&sortBy=&onlyForeignCountry=&countryIds=&sinceDate=&subcategoryIds=" target="_blank" rel="noreferrer"> LINK </a> revolucionaria en Express que te brinda acceso a información laboral completa y adaptada a tus necesidades. Gracias a esta API, puedes filtrar las ofertas laborales según provincia, ciudad, opción de teletrabajo, categoría de trabajo, nivel educativo requerido, jornada laboral, tipo de contrato y país. Los filtros flexibles te permiten encontrar exactamente lo que buscas.</p>
                        <br />
                        <p>Nuestra API te ofrece acceso directo a todas las ofertas laborales actuales publicadas en Infojobs. Con total libertad y sin restricciones, podrás aprovechar al máximo todas las oportunidades disponibles. Prepárate para descubrir tu próximo desafío profesional sin barreras</p>
                        <br />
                      </div>
                    </li>
                  </ul>

                </div>
              </div>

            </div>
          </div>
          <RecentOrders />
        </div>
      </main>
    </>
  )
}
